version: "3"

services:
  users_db:
    ports:
      - "5432:5432"
    container_name: taskmanager
    image: postgres:16.4
    environment:
      POSTGRES_DB: taskmanager
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root